title:             Bao Nguyen Yam's Blog
email:             baonguyenyam@gmail.com
description:       Tôi là Bảo Nguyên hiện là Full-Stack Developer tại nhiều công ty Nhật, USA, Singapore... Tôi cũng là giảng viên tại FPT.
author:            Bao Nguyen
baseurl:           ""
url:               "https://baonguyenyam.github.io/blog"
permalink: /404.html
# Social Profiles
channel_username:  baonguyenyam
github_username:   baonguyenyam
facebook_username: pham.nguyen.bao.nguyen

sass:
  add_charset: true
  sass_dir: _sass
  style: :compressed
compress_html:
  clippings: all
  comments: [""]
  endings: [html, head, body, li, dt, dd, rt, rp, optgroup, option, colgroup, caption, thead, tbody, tfoot, tr, td, th]
  profile: false
  blanklines: false
  ignore:
    envs: []
# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-minifier
jekyll_admin:
  hidden_links:
    # - posts
    # - pages
    # - staticfiles
    - datafiles
    - configuration
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: post-single
      title: ""
      subtitle: ""
      date:  2018-06-07 10:45:13 -0400
      background: null 
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: page
      title: ""
      description: ""
      background: null 