title:             Bao Nguyen Yam's Blog
email:             baonguyenyam@gmail.com
description:       Tôi là Bảo Nguyên hiện là Full-Stack Developer tại nhiều công ty Nhật, USA, Singapore... Tôi cũng là giảng viên tại FPT.
author:            Bao Nguyen
baseurl:           ""
url:               "https://baonguyenyam.github.io/blog"

# Social Profiles
twitter_username:  baonguyenyam
github_username:   baonguyenyam
facebook_username: pham.nguyen.bao.nguyen

sass:
  add_charset: true
  sass_dir: _sass
  style: :compressed
  
# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  # - jekyll-seo-tag